#![forbid(unsafe_code)]

use std::error::Error;
use std::ffi::{OsStr, OsString};
use std::fs::{DirBuilder, File, OpenOptions};
use std::io::{self, Read as _, Write as _};
use std::net::{IpAddr, Ipv4Addr, SocketAddr, TcpStream as StdTcpStream};
use std::path::{Path, PathBuf};
use std::time::Duration;
use synapsegit_lp_local_server::{ServerConfig, StudioState, editor_router, preview_router};
use tokio::net::TcpListener;
use tracing_subscriber::EnvFilter;
use uuid::Uuid;

const DEFAULT_LOG_LEVEL: &str = "info";
const CONTAINER_MODE_ENV: &str = "LP_STUDIO_CONTAINER_MODE";
const OPENAI_API_KEY_FILE_ENV: &str = "OPENAI_API_KEY_FILE";
const MAX_PROVIDER_CREDENTIAL_FILE_BYTES: u64 = 2 * 1024;

#[derive(Clone, Debug, Eq, PartialEq)]
struct AdvertisedNetwork {
    editor_origin: String,
    editor_host: String,
    preview_listener_origin: String,
    preview_scope_base: String,
}

fn safe_log_level(value: Option<&str>) -> &'static str {
    match value.map(str::trim).map(str::to_ascii_lowercase).as_deref() {
        Some("off") => "off",
        Some("error") => "error",
        Some("warn") => "warn",
        Some("info") => "info",
        Some("debug") => "debug",
        Some("trace") => "trace",
        _ => DEFAULT_LOG_LEVEL,
    }
}

fn safe_env_filter(value: Option<&str>) -> EnvFilter {
    // Dependency targets are disabled even at the maximum supported level.
    // Callers can choose an app level, but cannot inject an EnvFilter directive
    // that would turn provider/client internals into a logging surface.
    let level = safe_log_level(value);
    EnvFilter::new(format!("off,synapsegit_lp_local_server={level}"))
}

struct StateRootLease {
    path: PathBuf,
    remove_on_drop: bool,
    lock: Option<File>,
}

impl StateRootLease {
    fn from_environment() -> io::Result<Self> {
        match std::env::var_os("LP_STUDIO_STATE_ROOT") {
            Some(path) => Self::retained(PathBuf::from(path)),
            None => Self::autogenerated_in(&std::env::temp_dir()),
        }
    }

    fn retained(path: PathBuf) -> io::Result<Self> {
        ensure_private_persistent_directory(&path)?;
        let lock = acquire_state_root_lock(&path)?;
        Ok(Self {
            path,
            remove_on_drop: false,
            lock: Some(lock),
        })
    }

    fn autogenerated_in(parent: &Path) -> io::Result<Self> {
        for _ in 0..8 {
            let path = parent.join(format!("synapsegit-lp-studio-{}", Uuid::new_v4().simple()));
            match create_private_directory(&path) {
                Ok(()) => {
                    let lock = match acquire_state_root_lock(&path) {
                        Ok(lock) => lock,
                        Err(error) => {
                            let _ = std::fs::remove_dir_all(&path);
                            return Err(error);
                        }
                    };
                    return Ok(Self {
                        path,
                        remove_on_drop: true,
                        lock: Some(lock),
                    });
                }
                Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
                Err(error) => return Err(error),
            }
        }
        Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            "could not allocate a private local state directory",
        ))
    }

    fn path(&self) -> &Path {
        &self.path
    }
}

impl Drop for StateRootLease {
    fn drop(&mut self) {
        drop(self.lock.take());
        if self.remove_on_drop
            && let Err(error) = std::fs::remove_dir_all(&self.path)
            && error.kind() != io::ErrorKind::NotFound
        {
            tracing::warn!("could not remove autogenerated local state directory");
        }
    }
}

fn acquire_state_root_lock(path: &Path) -> io::Result<File> {
    let lock_path = path.join(".lp-studio.lock");
    match std::fs::symlink_metadata(&lock_path) {
        Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_file() => {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "state root lock must be a real regular file",
            ));
        }
        Ok(_) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => return Err(error),
    }

    let mut options = OpenOptions::new();
    options.read(true).write(true).create(true).truncate(false);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt as _;
        options.mode(0o600).custom_flags(libc::O_NOFOLLOW);
    }
    let lock = options.open(&lock_path)?;
    let metadata = lock.metadata()?;
    if !metadata.is_file() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "state root lock must be a regular file",
        ));
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::{MetadataExt as _, PermissionsExt as _};
        if metadata.nlink() != 1 || metadata.permissions().mode() & 0o077 != 0 {
            return Err(io::Error::new(
                io::ErrorKind::PermissionDenied,
                "state root lock must be private and unaliased",
            ));
        }
    }
    fs2::FileExt::try_lock_exclusive(&lock).map_err(|error| {
        let kind = if error.kind() == io::ErrorKind::WouldBlock {
            io::ErrorKind::AddrInUse
        } else {
            error.kind()
        };
        io::Error::new(kind, "LP_STUDIO_STATE_ROOT is already in use")
    })?;
    Ok(lock)
}

#[cfg(unix)]
fn create_private_directory(path: &Path) -> io::Result<()> {
    use std::os::unix::fs::{DirBuilderExt as _, PermissionsExt as _};

    let mut builder = DirBuilder::new();
    builder.mode(0o700).create(path)?;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o700))
}

#[cfg(unix)]
fn ensure_private_persistent_directory(path: &Path) -> io::Result<()> {
    use std::os::unix::fs::PermissionsExt as _;

    match std::fs::symlink_metadata(path) {
        Ok(metadata) => {
            if metadata.file_type().is_symlink() || !metadata.is_dir() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "LP_STUDIO_STATE_ROOT must be a real directory",
                ));
            }
            let mode = metadata.permissions().mode() & 0o777;
            if mode != 0o700 {
                return Err(io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    format!("LP_STUDIO_STATE_ROOT must have mode 0700; found {mode:04o}"),
                ));
            }
            Ok(())
        }
        Err(error) if error.kind() == io::ErrorKind::NotFound => create_private_directory(path),
        Err(error) => Err(error),
    }
}

#[cfg(not(unix))]
fn ensure_private_persistent_directory(path: &Path) -> io::Result<()> {
    match std::fs::symlink_metadata(path) {
        Ok(metadata) if metadata.is_dir() && !metadata.file_type().is_symlink() => Ok(()),
        Ok(_) => Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "LP_STUDIO_STATE_ROOT must be a real directory",
        )),
        Err(error) if error.kind() == io::ErrorKind::NotFound => create_private_directory(path),
        Err(error) => Err(error),
    }
}

#[cfg(not(unix))]
fn create_private_directory(path: &Path) -> io::Result<()> {
    DirBuilder::new().create(path)
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    if healthcheck_mode(std::env::args_os().skip(1))? {
        run_container_healthcheck()?;
        return Ok(());
    }

    tracing_subscriber::fmt()
        .with_env_filter(safe_env_filter(std::env::var("RUST_LOG").ok().as_deref()))
        .with_target(false)
        .with_ansi(false)
        .with_writer(std::io::stderr)
        .init();

    let container_mode = container_mode_from_env()?;
    let editor_port = port_from_env("LP_STUDIO_EDITOR_PORT")?;
    let preview_port = port_from_env("LP_STUDIO_PREVIEW_PORT")?;
    validate_container_ports(container_mode, editor_port, preview_port)?;
    let editor_listener = bind_listener(editor_port, container_mode).await?;
    let preview_listener = bind_listener(preview_port, container_mode).await?;
    let editor_address = editor_listener.local_addr()?;
    let preview_address = preview_listener.local_addr()?;
    let advertised = advertised_network(editor_address, preview_address);
    // Autogenerated roots are process-owned, private, and ephemeral. An
    // explicitly supplied root is caller-owned and intentionally retained.
    let state_root = StateRootLease::from_environment()?;
    let web_dist = std::env::var_os("LP_STUDIO_WEB_DIST")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("apps/web/dist"));
    let import_root = std::env::var_os("LP_STUDIO_IMPORT_ROOT")
        .map(PathBuf::from)
        .map(|path| validate_import_root(&path, state_root.path()))
        .transpose()?;
    let mut server_config = ServerConfig::new(
        &advertised.editor_origin,
        &advertised.editor_host,
        &advertised.preview_scope_base,
        state_root.path().to_path_buf(),
        web_dist,
    )
    .with_import_root(import_root);
    if let Some(api_key) = openai_api_key_from_environment()? {
        let model =
            std::env::var("LP_STUDIO_OPENAI_MODEL").unwrap_or_else(|_| "gpt-5.4-mini".into());
        server_config = server_config.with_openai(api_key, model)?;
    }
    let (state, operating_mode) = match StudioState::new(server_config.clone()) {
        Ok(state) => (state, "normal"),
        Err(normal_error) => match StudioState::new_recovery(server_config) {
            Ok(state) => {
                tracing::warn!(
                    code = "managed_storage_read_only_recovery",
                    "managed storage opened in read-only recovery mode"
                );
                (state, "read_only_recovery")
            }
            Err(_) => return Err(normal_error.into()),
        },
    };

    println!(
        "LP_STUDIO_READY {}",
        serde_json::json!({
            "editorOrigin": advertised.editor_origin,
            "previewOrigin": advertised.preview_listener_origin,
            "operatingMode": operating_mode,
        })
    );

    let preview_state = state.clone();
    let preview_task = tokio::spawn(async move {
        axum::serve(
            preview_listener,
            preview_router(preview_state).into_make_service(),
        )
        .await
    });
    let editor_result = axum::serve(editor_listener, editor_router(state).into_make_service())
        .with_graceful_shutdown(shutdown_signal())
        .await;
    preview_task.abort();
    let _ = preview_task.await;
    editor_result?;
    Ok(())
}

fn advertised_network(
    editor_address: SocketAddr,
    preview_address: SocketAddr,
) -> AdvertisedNetwork {
    let editor_host = format!("127.0.0.1:{}", editor_address.port());
    AdvertisedNetwork {
        editor_origin: format!("http://{editor_host}"),
        editor_host,
        preview_listener_origin: format!("http://127.0.0.1:{}", preview_address.port()),
        preview_scope_base: format!("http://localhost:{}", preview_address.port()),
    }
}

fn container_mode_from_env() -> Result<bool, Box<dyn Error>> {
    parse_container_mode(std::env::var_os(CONTAINER_MODE_ENV).as_deref())
        .map_err(|error| error.into())
}

fn parse_container_mode(value: Option<&OsStr>) -> Result<bool, &'static str> {
    match value {
        None => Ok(false),
        Some(value) if value == OsStr::new("1") => Ok(true),
        Some(_) => Err("LP_STUDIO_CONTAINER_MODE must be exactly 1 when present"),
    }
}

fn validate_container_ports(
    container_mode: bool,
    editor_port: u16,
    preview_port: u16,
) -> Result<(), &'static str> {
    if !container_mode {
        return Ok(());
    }
    if editor_port < 1024 || preview_port < 1024 {
        return Err("container mode requires explicit unprivileged Editor and Preview ports");
    }
    if editor_port == preview_port {
        return Err("container mode requires distinct Editor and Preview ports");
    }
    Ok(())
}

fn port_from_env(name: &str) -> Result<u16, Box<dyn Error>> {
    match std::env::var(name) {
        Ok(value) => value
            .parse::<u16>()
            .map_err(|_| format!("{name} must be a TCP port in 0..=65535").into()),
        Err(std::env::VarError::NotPresent) => Ok(0),
        Err(error) => Err(error.into()),
    }
}

fn healthcheck_mode(arguments: impl IntoIterator<Item = OsString>) -> Result<bool, &'static str> {
    let mut arguments = arguments.into_iter();
    match (arguments.next(), arguments.next()) {
        (None, None) => Ok(false),
        (Some(argument), None) if argument == OsStr::new("--healthcheck") => Ok(true),
        _ => Err("the only supported argument is --healthcheck"),
    }
}

fn run_container_healthcheck() -> Result<(), Box<dyn Error>> {
    let container_mode = container_mode_from_env()?;
    let editor_port = port_from_env("LP_STUDIO_EDITOR_PORT")?;
    let preview_port = port_from_env("LP_STUDIO_PREVIEW_PORT")?;
    validate_container_ports(container_mode, editor_port, preview_port)?;
    if !container_mode {
        return Err("--healthcheck requires LP_STUDIO_CONTAINER_MODE=1".into());
    }
    check_health_listener(editor_port, "editor")?;
    check_health_listener(preview_port, "preview")?;
    Ok(())
}

fn check_health_listener(port: u16, expected_role: &str) -> io::Result<()> {
    const HEALTHCHECK_TIMEOUT: Duration = Duration::from_secs(1);
    const MAX_HEALTH_RESPONSE_BYTES: u64 = 4 * 1024;

    let address = SocketAddr::new(IpAddr::V4(Ipv4Addr::LOCALHOST), port);
    let mut stream = StdTcpStream::connect_timeout(&address, HEALTHCHECK_TIMEOUT)?;
    stream.set_read_timeout(Some(HEALTHCHECK_TIMEOUT))?;
    stream.set_write_timeout(Some(HEALTHCHECK_TIMEOUT))?;
    write!(
        stream,
        "GET /health HTTP/1.1\r\nHost: 127.0.0.1:{port}\r\nConnection: close\r\n\r\n"
    )?;
    stream.flush()?;
    let mut response = Vec::new();
    (&mut stream)
        .take(MAX_HEALTH_RESPONSE_BYTES + 1)
        .read_to_end(&mut response)?;
    if response.len() as u64 > MAX_HEALTH_RESPONSE_BYTES
        || !valid_health_response(&response, expected_role)
    {
        return Err(io::Error::other("container listener healthcheck failed"));
    }
    Ok(())
}

fn valid_health_response(response: &[u8], expected_role: &str) -> bool {
    let Ok(response) = std::str::from_utf8(response) else {
        return false;
    };
    let Some((headers, body)) = response.split_once("\r\n\r\n") else {
        return false;
    };
    if headers.lines().next() != Some("HTTP/1.1 200 OK") {
        return false;
    }
    let Ok(body) = serde_json::from_str::<serde_json::Value>(body) else {
        return false;
    };
    let Some(body) = body.as_object() else {
        return false;
    };
    body.len() == 3
        && body.get("schemaVersion").and_then(|value| value.as_str()) == Some("1")
        && body.get("status").and_then(|value| value.as_str()) == Some("ok")
        && body.get("role").and_then(|value| value.as_str()) == Some(expected_role)
}

fn openai_api_key_from_environment() -> io::Result<Option<String>> {
    load_openai_api_key(
        std::env::var_os("OPENAI_API_KEY"),
        std::env::var_os(OPENAI_API_KEY_FILE_ENV).map(PathBuf::from),
    )
}

fn load_openai_api_key(
    inline_key: Option<OsString>,
    key_file: Option<PathBuf>,
) -> io::Result<Option<String>> {
    match (inline_key, key_file) {
        (Some(_), Some(_)) => Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "OPENAI_API_KEY and OPENAI_API_KEY_FILE are mutually exclusive",
        )),
        (Some(key), None) => key.into_string().map(Some).map_err(|_| {
            io::Error::new(io::ErrorKind::InvalidInput, "OPENAI_API_KEY must be UTF-8")
        }),
        (None, Some(path)) => read_provider_credential_file(&path).map(Some),
        (None, None) => Ok(None),
    }
}

fn read_provider_credential_file(path: &Path) -> io::Result<String> {
    let path_metadata = std::fs::symlink_metadata(path)?;
    if path_metadata.file_type().is_symlink() || !path_metadata.is_file() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "OPENAI_API_KEY_FILE must be a real regular file",
        ));
    }
    if path_metadata.len() > MAX_PROVIDER_CREDENTIAL_FILE_BYTES {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "OPENAI_API_KEY_FILE is too large",
        ));
    }

    let mut options = OpenOptions::new();
    options.read(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt as _;
        options.custom_flags(libc::O_NOFOLLOW);
    }
    let mut file = options.open(path)?;
    let opened_metadata = file.metadata()?;
    if !opened_metadata.is_file() || opened_metadata.len() > MAX_PROVIDER_CREDENTIAL_FILE_BYTES {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "OPENAI_API_KEY_FILE must be a bounded regular file",
        ));
    }

    let mut key = String::new();
    file.read_to_string(&mut key).map_err(|error| {
        if error.kind() == io::ErrorKind::InvalidData {
            io::Error::new(
                io::ErrorKind::InvalidInput,
                "OPENAI_API_KEY_FILE must be UTF-8",
            )
        } else {
            error
        }
    })?;
    if key.ends_with('\n') {
        key.pop();
        if key.ends_with('\r') {
            key.pop();
        }
    }
    Ok(key)
}

fn validate_import_root(import_root: &Path, state_root: &Path) -> io::Result<PathBuf> {
    let import_metadata = std::fs::symlink_metadata(import_root)?;
    if import_metadata.file_type().is_symlink() || !import_metadata.is_dir() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "LP_STUDIO_IMPORT_ROOT must be a real directory",
        ));
    }
    let state_metadata = std::fs::symlink_metadata(state_root)?;
    if state_metadata.file_type().is_symlink() || !state_metadata.is_dir() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "LP_STUDIO_STATE_ROOT must be a real directory",
        ));
    }
    let import_canonical = std::fs::canonicalize(import_root)?;
    let state_canonical = std::fs::canonicalize(state_root)?;
    if import_canonical == state_canonical
        || import_canonical.starts_with(&state_canonical)
        || state_canonical.starts_with(&import_canonical)
    {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "LP_STUDIO_IMPORT_ROOT and LP_STUDIO_STATE_ROOT must not overlap",
        ));
    }
    Ok(import_canonical)
}

async fn bind_listener(port: u16, container_mode: bool) -> std::io::Result<TcpListener> {
    let address = if container_mode {
        Ipv4Addr::UNSPECIFIED
    } else {
        Ipv4Addr::LOCALHOST
    };
    TcpListener::bind(SocketAddr::new(IpAddr::V4(address), port)).await
}

async fn shutdown_signal() {
    #[cfg(unix)]
    {
        match tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate()) {
            Ok(mut terminate) => {
                tokio::select! {
                    result = tokio::signal::ctrl_c() => {
                        if let Err(error) = result {
                            tracing::warn!(%error, "failed to receive interrupt signal");
                        }
                    }
                    _ = terminate.recv() => {}
                }
            }
            Err(error) => {
                tracing::warn!(%error, "failed to install termination signal handler");
                let _ = tokio::signal::ctrl_c().await;
            }
        }
    }
    #[cfg(not(unix))]
    if let Err(error) = tokio::signal::ctrl_c().await {
        tracing::warn!(%error, "failed to receive interrupt signal");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn log_level_is_an_exact_allow_list_not_an_env_filter_directive() {
        for level in ["off", "error", "warn", "info", "debug", "trace"] {
            assert_eq!(safe_log_level(Some(level)), level);
            assert_eq!(safe_log_level(Some(&level.to_ascii_uppercase())), level);
        }
        assert_eq!(safe_log_level(None), DEFAULT_LOG_LEVEL);
        assert_eq!(safe_log_level(Some("")), DEFAULT_LOG_LEVEL);
        assert_eq!(safe_log_level(Some("reqwest=trace")), DEFAULT_LOG_LEVEL);
        assert_eq!(safe_log_level(Some("trace,hyper=trace")), DEFAULT_LOG_LEVEL);
    }

    #[test]
    fn advertised_network_is_loopback_even_for_container_listeners() {
        let advertised = advertised_network(
            SocketAddr::new(IpAddr::V4(Ipv4Addr::UNSPECIFIED), 4173),
            SocketAddr::new(IpAddr::V4(Ipv4Addr::UNSPECIFIED), 4174),
        );
        assert_eq!(advertised.editor_origin, "http://127.0.0.1:4173");
        assert_eq!(advertised.editor_host, "127.0.0.1:4173");
        assert_eq!(advertised.preview_listener_origin, "http://127.0.0.1:4174");
        assert_eq!(advertised.preview_scope_base, "http://localhost:4174");
    }

    #[test]
    fn container_mode_is_an_exact_opt_in() {
        assert!(!parse_container_mode(None).unwrap());
        assert!(parse_container_mode(Some(OsStr::new("1"))).unwrap());
        for invalid in ["", "0", "true", "yes", " 1"] {
            assert!(parse_container_mode(Some(OsStr::new(invalid))).is_err());
        }
    }

    #[test]
    fn container_ports_are_fixed_unprivileged_and_distinct() {
        assert!(validate_container_ports(true, 4173, 4174).is_ok());
        assert!(validate_container_ports(true, 0, 4174).is_err());
        assert!(validate_container_ports(true, 80, 4174).is_err());
        assert!(validate_container_ports(true, 4173, 4173).is_err());
        assert!(validate_container_ports(false, 0, 0).is_ok());
    }

    #[test]
    fn healthcheck_argument_is_exact_and_exclusive() {
        assert!(!healthcheck_mode(Vec::<OsString>::new()).unwrap());
        assert!(healthcheck_mode([OsString::from("--healthcheck")]).unwrap());
        for invalid in [
            vec![OsString::from("healthcheck")],
            vec![OsString::from("--healthcheck"), OsString::from("extra")],
        ] {
            assert!(healthcheck_mode(invalid).is_err());
        }
    }

    #[test]
    fn healthcheck_response_requires_the_exact_role_and_shape() {
        let valid = b"HTTP/1.1 200 OK\r\ncontent-type: application/json\r\n\r\n{\"schemaVersion\":\"1\",\"status\":\"ok\",\"role\":\"editor\"}";
        assert!(valid_health_response(valid, "editor"));
        assert!(!valid_health_response(valid, "preview"));
        assert!(!valid_health_response(
            b"HTTP/1.1 200 OK\r\n\r\n{\"schemaVersion\":\"1\",\"status\":\"ok\",\"role\":\"editor\",\"extra\":true}",
            "editor"
        ));
        assert!(!valid_health_response(
            b"HTTP/1.1 503 Service Unavailable\r\n\r\n{}",
            "editor"
        ));
    }

    #[test]
    fn provider_credential_file_accepts_one_trailing_line_ending() {
        let parent = tempfile::tempdir().expect("temporary parent");
        let path = parent.path().join("openai-key");
        std::fs::write(&path, b"test-provider-key\r\n").expect("credential file");
        assert_eq!(
            load_openai_api_key(None, Some(path)).unwrap(),
            Some("test-provider-key".into())
        );
    }

    #[test]
    fn provider_credential_sources_are_mutually_exclusive() {
        let parent = tempfile::tempdir().expect("temporary parent");
        let path = parent.path().join("openai-key");
        std::fs::write(&path, b"file-key").expect("credential file");
        let error = load_openai_api_key(Some(OsString::from("inline-key")), Some(path))
            .expect_err("two credential sources must fail");
        assert_eq!(error.kind(), io::ErrorKind::InvalidInput);
    }

    #[cfg(unix)]
    #[test]
    fn provider_credential_file_rejects_symlinks() {
        use std::os::unix::fs::symlink;

        let parent = tempfile::tempdir().expect("temporary parent");
        let target = parent.path().join("target");
        let link = parent.path().join("openai-key");
        std::fs::write(&target, b"file-key").expect("credential file");
        symlink(&target, &link).expect("credential symlink");
        let error =
            load_openai_api_key(None, Some(link)).expect_err("credential symlink must fail");
        assert_eq!(error.kind(), io::ErrorKind::InvalidInput);
    }

    #[test]
    fn autogenerated_state_root_is_removed_on_drop() {
        let parent = tempfile::tempdir().expect("temporary parent");
        let root = StateRootLease::autogenerated_in(parent.path()).expect("private state root");
        let path = root.path().to_path_buf();
        std::fs::write(path.join("private-context"), b"private").expect("state file");
        assert!(path.exists());
        drop(root);
        assert!(!path.exists());
    }

    #[cfg(unix)]
    #[test]
    fn autogenerated_state_root_is_owner_only() {
        use std::os::unix::fs::PermissionsExt as _;

        let parent = tempfile::tempdir().expect("temporary parent");
        let root = StateRootLease::autogenerated_in(parent.path()).expect("private state root");
        let mode = std::fs::metadata(root.path())
            .expect("state root metadata")
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o700);
    }

    #[test]
    fn caller_owned_state_root_is_retained() {
        let parent = tempfile::tempdir().expect("temporary parent");
        let path = parent.path().join("retained-state");
        drop(StateRootLease::retained(path.clone()).expect("retained state root"));
        assert!(path.exists());
    }

    #[test]
    fn caller_owned_state_root_allows_only_one_live_lease() {
        let parent = tempfile::tempdir().expect("temporary parent");
        let path = parent.path().join("exclusive-state");
        let first = StateRootLease::retained(path.clone()).expect("first lease");
        let error = StateRootLease::retained(path.clone())
            .err()
            .expect("second lease must fail");
        assert_eq!(error.kind(), io::ErrorKind::AddrInUse);
        assert!(error.to_string().contains("already in use"));
        drop(first);
        drop(StateRootLease::retained(path).expect("lease after release"));
    }

    #[test]
    fn import_and_state_roots_must_be_real_disjoint_directories() {
        let parent = tempfile::tempdir().expect("temporary parent");

        let equal = parent.path().join("equal");
        std::fs::create_dir(&equal).unwrap();
        let error = validate_import_root(&equal, &equal).unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::InvalidInput);

        let import_parent = parent.path().join("import-parent");
        let nested_state = import_parent.join("state");
        std::fs::create_dir(&import_parent).unwrap();
        std::fs::create_dir(&nested_state).unwrap();
        let error = validate_import_root(&import_parent, &nested_state).unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::InvalidInput);

        let state_parent = parent.path().join("state-parent");
        let nested_import = state_parent.join("site");
        std::fs::create_dir(&state_parent).unwrap();
        std::fs::create_dir(&nested_import).unwrap();
        let error = validate_import_root(&nested_import, &state_parent).unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::InvalidInput);

        let disjoint_state = parent.path().join("disjoint-state");
        let disjoint_import = parent.path().join("disjoint-import");
        std::fs::create_dir(&disjoint_state).unwrap();
        std::fs::create_dir(&disjoint_import).unwrap();
        assert_eq!(
            validate_import_root(&disjoint_import, &disjoint_state).unwrap(),
            std::fs::canonicalize(&disjoint_import).unwrap()
        );
    }

    #[cfg(unix)]
    #[test]
    fn import_root_symlink_fails_closed() {
        use std::os::unix::fs::symlink;

        let parent = tempfile::tempdir().expect("temporary parent");
        let state = parent.path().join("state");
        let target = parent.path().join("target");
        let link = parent.path().join("import-link");
        std::fs::create_dir(&state).unwrap();
        std::fs::create_dir(&target).unwrap();
        symlink(&target, &link).unwrap();
        let error = validate_import_root(&link, &state).unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::InvalidInput);
    }

    #[cfg(unix)]
    #[test]
    fn newly_created_caller_owned_state_root_is_owner_only() {
        use std::os::unix::fs::PermissionsExt as _;

        let parent = tempfile::tempdir().expect("temporary parent");
        let path = parent.path().join("persistent-private-state");
        let root = StateRootLease::retained(path.clone()).expect("persistent state root");
        let mode = std::fs::metadata(root.path())
            .expect("state root metadata")
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o700);
        drop(root);
        assert!(path.exists());
    }

    #[cfg(unix)]
    #[test]
    fn insecure_existing_caller_owned_state_root_fails_closed() {
        use std::os::unix::fs::PermissionsExt as _;

        let parent = tempfile::tempdir().expect("temporary parent");
        let path = parent.path().join("insecure-state");
        std::fs::create_dir(&path).expect("state root");
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o750))
            .expect("insecure mode");
        let error = StateRootLease::retained(path)
            .err()
            .expect("insecure state root must fail");
        assert_eq!(error.kind(), io::ErrorKind::PermissionDenied);
        assert!(error.to_string().contains("mode 0700"));
    }

    #[cfg(unix)]
    #[test]
    fn symlink_caller_owned_state_root_fails_closed() {
        use std::os::unix::fs::symlink;

        let parent = tempfile::tempdir().expect("temporary parent");
        let target = parent.path().join("target");
        let link = parent.path().join("state-link");
        std::fs::create_dir(&target).expect("target");
        symlink(&target, &link).expect("state symlink");
        let error = StateRootLease::retained(link)
            .err()
            .expect("symlink state root must fail");
        assert_eq!(error.kind(), io::ErrorKind::InvalidInput);
    }
}
