#![forbid(unsafe_code)]

use std::error::Error;
use std::fs::DirBuilder;
use std::io;
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use std::path::{Path, PathBuf};
use synapsegit_lp_local_server::{ServerConfig, StudioState, editor_router, preview_router};
use tokio::net::TcpListener;
use tracing_subscriber::EnvFilter;
use uuid::Uuid;

struct StateRootLease {
    path: PathBuf,
    remove_on_drop: bool,
}

impl StateRootLease {
    fn from_environment() -> io::Result<Self> {
        match std::env::var_os("LP_STUDIO_STATE_ROOT") {
            Some(path) => Self::retained(PathBuf::from(path)),
            None => Self::autogenerated_in(&std::env::temp_dir()),
        }
    }

    fn retained(path: PathBuf) -> io::Result<Self> {
        ensure_private_persistent_directory(&path)?;
        Ok(Self {
            path,
            remove_on_drop: false,
        })
    }

    fn autogenerated_in(parent: &Path) -> io::Result<Self> {
        for _ in 0..8 {
            let path = parent.join(format!("synapsegit-lp-studio-{}", Uuid::new_v4().simple()));
            match create_private_directory(&path) {
                Ok(()) => {
                    return Ok(Self {
                        path,
                        remove_on_drop: true,
                    });
                }
                Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
                Err(error) => return Err(error),
            }
        }
        Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            "could not allocate a private local state directory",
        ))
    }

    fn path(&self) -> &Path {
        &self.path
    }
}

impl Drop for StateRootLease {
    fn drop(&mut self) {
        if self.remove_on_drop
            && let Err(error) = std::fs::remove_dir_all(&self.path)
            && error.kind() != io::ErrorKind::NotFound
        {
            tracing::warn!("could not remove autogenerated local state directory");
        }
    }
}

#[cfg(unix)]
fn create_private_directory(path: &Path) -> io::Result<()> {
    use std::os::unix::fs::{DirBuilderExt as _, PermissionsExt as _};

    let mut builder = DirBuilder::new();
    builder.mode(0o700).create(path)?;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o700))
}

#[cfg(unix)]
fn ensure_private_persistent_directory(path: &Path) -> io::Result<()> {
    use std::os::unix::fs::PermissionsExt as _;

    match std::fs::symlink_metadata(path) {
        Ok(metadata) => {
            if metadata.file_type().is_symlink() || !metadata.is_dir() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "LP_STUDIO_STATE_ROOT must be a real directory",
                ));
            }
            let mode = metadata.permissions().mode() & 0o777;
            if mode != 0o700 {
                return Err(io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    format!("LP_STUDIO_STATE_ROOT must have mode 0700; found {mode:04o}"),
                ));
            }
            Ok(())
        }
        Err(error) if error.kind() == io::ErrorKind::NotFound => create_private_directory(path),
        Err(error) => Err(error),
    }
}

#[cfg(not(unix))]
fn ensure_private_persistent_directory(path: &Path) -> io::Result<()> {
    match std::fs::symlink_metadata(path) {
        Ok(metadata) if metadata.is_dir() && !metadata.file_type().is_symlink() => Ok(()),
        Ok(_) => Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "LP_STUDIO_STATE_ROOT must be a real directory",
        )),
        Err(error) if error.kind() == io::ErrorKind::NotFound => create_private_directory(path),
        Err(error) => Err(error),
    }
}

#[cfg(not(unix))]
fn create_private_directory(path: &Path) -> io::Result<()> {
    DirBuilder::new().create(path)
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .with_target(false)
        .init();

    let editor_listener = bind_local(port_from_env("LP_STUDIO_EDITOR_PORT")?).await?;
    let preview_listener = bind_local(port_from_env("LP_STUDIO_PREVIEW_PORT")?).await?;
    let editor_address = editor_listener.local_addr()?;
    let preview_address = preview_listener.local_addr()?;
    let editor_origin = format!("http://{editor_address}");
    let preview_origin = format!("http://{preview_address}");
    // Autogenerated roots are process-owned, private, and ephemeral. An
    // explicitly supplied root is caller-owned and intentionally retained.
    let state_root = StateRootLease::from_environment()?;
    let web_dist = std::env::var_os("LP_STUDIO_WEB_DIST")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("apps/web/dist"));
    let state = StudioState::new(ServerConfig::new(
        &editor_origin,
        editor_address.to_string(),
        &preview_origin,
        state_root.path().to_path_buf(),
        web_dist,
    ))?;

    println!(
        "LP_STUDIO_READY {}",
        serde_json::json!({
            "editorOrigin": editor_origin,
            "previewOrigin": preview_origin,
        })
    );

    let preview_state = state.clone();
    let preview_task = tokio::spawn(async move {
        axum::serve(
            preview_listener,
            preview_router(preview_state).into_make_service(),
        )
        .await
    });
    let editor_result = axum::serve(editor_listener, editor_router(state).into_make_service())
        .with_graceful_shutdown(shutdown_signal())
        .await;
    preview_task.abort();
    let _ = preview_task.await;
    editor_result?;
    Ok(())
}

fn port_from_env(name: &str) -> Result<u16, Box<dyn Error>> {
    match std::env::var(name) {
        Ok(value) => value
            .parse::<u16>()
            .map_err(|_| format!("{name} must be a TCP port in 0..=65535").into()),
        Err(std::env::VarError::NotPresent) => Ok(0),
        Err(error) => Err(error.into()),
    }
}

async fn bind_local(port: u16) -> std::io::Result<TcpListener> {
    TcpListener::bind(SocketAddr::new(IpAddr::V4(Ipv4Addr::LOCALHOST), port)).await
}

async fn shutdown_signal() {
    if let Err(error) = tokio::signal::ctrl_c().await {
        tracing::warn!(%error, "failed to install shutdown signal handler");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn autogenerated_state_root_is_removed_on_drop() {
        let parent = tempfile::tempdir().expect("temporary parent");
        let root = StateRootLease::autogenerated_in(parent.path()).expect("private state root");
        let path = root.path().to_path_buf();
        std::fs::write(path.join("private-context"), b"private").expect("state file");
        assert!(path.exists());
        drop(root);
        assert!(!path.exists());
    }

    #[cfg(unix)]
    #[test]
    fn autogenerated_state_root_is_owner_only() {
        use std::os::unix::fs::PermissionsExt as _;

        let parent = tempfile::tempdir().expect("temporary parent");
        let root = StateRootLease::autogenerated_in(parent.path()).expect("private state root");
        let mode = std::fs::metadata(root.path())
            .expect("state root metadata")
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o700);
    }

    #[test]
    fn caller_owned_state_root_is_retained() {
        let parent = tempfile::tempdir().expect("temporary parent");
        let path = parent.path().join("retained-state");
        drop(StateRootLease::retained(path.clone()).expect("retained state root"));
        assert!(path.exists());
    }

    #[cfg(unix)]
    #[test]
    fn newly_created_caller_owned_state_root_is_owner_only() {
        use std::os::unix::fs::PermissionsExt as _;

        let parent = tempfile::tempdir().expect("temporary parent");
        let path = parent.path().join("persistent-private-state");
        let root = StateRootLease::retained(path.clone()).expect("persistent state root");
        let mode = std::fs::metadata(root.path())
            .expect("state root metadata")
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o700);
        drop(root);
        assert!(path.exists());
    }

    #[cfg(unix)]
    #[test]
    fn insecure_existing_caller_owned_state_root_fails_closed() {
        use std::os::unix::fs::PermissionsExt as _;

        let parent = tempfile::tempdir().expect("temporary parent");
        let path = parent.path().join("insecure-state");
        std::fs::create_dir(&path).expect("state root");
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o750))
            .expect("insecure mode");
        let error = StateRootLease::retained(path)
            .err()
            .expect("insecure state root must fail");
        assert_eq!(error.kind(), io::ErrorKind::PermissionDenied);
        assert!(error.to_string().contains("mode 0700"));
    }

    #[cfg(unix)]
    #[test]
    fn symlink_caller_owned_state_root_fails_closed() {
        use std::os::unix::fs::symlink;

        let parent = tempfile::tempdir().expect("temporary parent");
        let target = parent.path().join("target");
        let link = parent.path().join("state-link");
        std::fs::create_dir(&target).expect("target");
        symlink(&target, &link).expect("state symlink");
        let error = StateRootLease::retained(link)
            .err()
            .expect("symlink state root must fail");
        assert_eq!(error.kind(), io::ErrorKind::InvalidInput);
    }
}
